spring:
  datasource:
#    db_mysql:
#      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: sql159159
#    db_h2:
#      driver-class-name: org.h2.Driver
#      schema: classpath:db/schema-h2.sql
#      data: classpath:db/data-h2.sql
#      url: jdbc:h2:mem:test
#      username: root
#      password: test
    lztj: # dev
      connection-init-sql: set names utf8mb4
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-8vbe6o359761y8pv66o.mysql.zhangbei.rds.aliyuncs.com:3306/lingzhu-rec-dev?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useAffectedRows=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: lingzhu_dev
      password: Pass2021@01%12
  h2:
    console:
      enabled: true
#  jpa:
#    database: MYSQL
#    show-sql: true
#
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  redis:
    # database: 1
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  mvc:
    view:
      prefix: classpath:/static
      suffix: .jsp

yanbdong:
  yy: 1
#hh:
#  a: 1
#  b: v
#  c: mm



