@startuml
|开发人员|
start
:定义**xxxWorkFlow**，存储在db中;
note right: db的结构？
|自定义BPM框架|
:new ProcessEngine: procEg;
:procEg.getRuntimeService(): rtSvc;
note right: 无deploy环节
:rtSvc.createProcessInstance("**xxxWorkFlow**"): procIns;
note right: 创建workflow实例
repeat
  :procIns.getCurrentTask(): task;
  note right: 获取workflow中的当前任务。
  |开发人员|
  :procIns.setVariable(T) || task.setVariable(T);
  note right: 为当前task设置入参
  |自定义BPM框架|
  :procIns.completeCurrentTask();
  note right
    阻塞方法，直到当前task结束。
  end note
  |业务模块|
  :命令模式执行task的biz逻辑;
  |自定义BPM框架|
  :procIns.completeCurrentTask();
  note right
  自动存贮当前task的结果在procIns中，
  并根据task结果以及**xxxWorkFlow**的定义,自动载入下一个task
  end note
repeat while (procIns.isDone?) is (no)
-> yes;
stop
@enduml